---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glances
  namespace: tools
  labels:
    app: glances
spec:
  rules:
    - host: stats.brzrkr.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glances
                port:
                  number: 61208
