---
apiVersion: v1
kind: Service
metadata:
  name: glances
  namespace: tools
  labels:
    app: glances
spec:
  type: ClusterIP
  ports:
    - port: 61208
      targetPort: 61208
      protocol: TCP
      name: web
  selector:
    app: glances
