---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.protonmail.ch:587'
      smtp_from: 'parker.anderson@brzrkr.io'
      smtp_auth_username: 'parker.anderson@brzrkr.io'
      smtp_auth_password: 'LCEL62NF32LXV54V'
      smtp_require_tls: true

    route:
      receiver: 'email'
      group_by: ['alertname', 'namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h

    receivers:
      - name: 'email'
        email_configs:
          - to: 'parker.anderson@brzrkr.io'
            send_resolved: true
            headers:
              Subject: '[HTPC] {{ .Status | toUpper }}: {{ .GroupLabels.alertname }}'
