---
# Root kustomization for the entire cluster
# FluxCD will apply this to reconcile all resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure
  - apps
